name: Build App
on:
  push:
    branches: [master]
    tags:
      - '*'

jobs:
  build_linux_amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21.0

      - name: Install libs linux
        run: sudo apt-get install gcc libgtk-3-dev libayatana-appindicator3-dev

      - name: Install dependences
        run: go mod download

      - name: Build
        run: go build -o ./sh-tray-icon_linux_amd64

      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: sh-tray-icon_linux_amd64
          path: ./sh-tray-icon_linux_amd64

  build_macos_amd64:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21.0

      - name: Install dependences
        run: go mod download

      - name: Build
        run: go build -o ./sh-tray-icon_macos_amd64

      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: sh-tray-icon_macos_amd64
          path: ./sh-tray-icon_macos_amd64

  build_windows_amd64:
    runs-on: windows-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21.0

      - name: Install dependences
        run: go mod download

      - name: Build
        run: go build -ldflags "-H=windowsgui" -o ./sh-tray-icon_windows_amd64.exe

      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: sh-tray-icon_windows_amd64
          path: ./sh-tray-icon_windows_amd64.exe

  release:
    runs-on: ubuntu-latest
    needs: [build_linux_amd64, build_macos_amd64, build_windows_amd64]
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@master

      - uses: actions/download-artifact@master
        with:
          name: sh-tray-icon_linux_amd64
          path: ./

      - uses: actions/download-artifact@master
        with:
          name: sh-tray-icon_macos_amd64
          path: ./

      - uses: actions/download-artifact@master
        with:
          name: sh-tray-icon_windows_amd64
          path: ./

      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}}

      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./sh-tray-icon_linux_amd64
          asset_name: sh-tray-icon_linux_amd64
          asset_content_type: application/zip
